const data = [
  {
    id: 1,
    name: "3d pen",
    subName: "3d pen",
    source: "Google Autocomplete",
    mode: "Manual",
    totalKws: "0/739",
    clusters: "0",
    language: "EN",
    createdAt: "Novenmber 9, 2022",
  },
  {
    id: 2,
    name: "3d pen",
    subName: "3d pen",
    source: "Google Autocomplete",
    mode: "Manual",
    totalKws: "0/739",
    clusters: "0",
    language: "EN",
    createdAt: "Novenmber 9, 2022",
  },
  {
    id: 3,
    name: "3d pen",
    subName: "3d pen",
    source: "Google Autocomplete",
    mode: "Manual",
    totalKws: "0/739",
    clusters: "0",
    language: "EN",
    createdAt: "Novenmber 9, 2022",
  },
  {
    id: 4,
    name: "3d pen",
    subName: "3d pen",
    source: "Google Autocomplete",
    mode: "Manual",
    totalKws: "0/739",
    clusters: "0",
    language: "EN",
    createdAt: "Novenmber 9, 2022",
  },
  {
    id: 5,
    name: "3d pen",
    subName: "3d pen",
    source: "Google Autocomplete",
    mode: "Manual",
    totalKws: "0/739",
    clusters: "0",
    language: "EN",
    createdAt: "Novenmber 9, 2022",
  },
  {
    id: 6,
    name: "3d pen",
    subName: "3d pen",
    source: "Google Autocomplete",
    mode: "Manual",
    totalKws: "0/739",
    clusters: "0",
    language: "EN",
    createdAt: "Novenmber 9, 2022",
  },
];

export default data;
